import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { loadModel } from '../src/model/validate.js'
import { graphvizRenderer, renderGraphvizSvg } from '../src/render/graphviz.js'

/**
 * The README embeds committed renders of the example. They are generated by
 * `npm run docs` and asserted in CI, but the failure they guard against —
 * changing the renderer and leaving the README showing the old picture — is
 * one you want to hear about before pushing, not after.
 */
describe('committed renders', () => {
  const model = loadModel(readFileSync(new URL('../examples/architecture.yaml', import.meta.url), 'utf8')).model!

  it('match what the renderer produces today', async () => {
    if (!(await graphvizRenderer.probe()).available) return // no WebAssembly here; CI covers it
    const committed = readFileSync(new URL('../docs/app.svg', import.meta.url), 'utf8')
    const fresh = await renderGraphvizSvg(model, { view: 'app', direction: 'LR' }, 'wasm')
    expect(fresh, 'docs/ is stale — run `npm run docs` and commit the result').toBe(committed)
  })

  it('are pinned to the bundled build, so a local `dot` cannot change them', async () => {
    if (!(await graphvizRenderer.probe()).available) return
    // Same call twice: layout must be byte-deterministic, or the freshness
    // check in CI would fail at random.
    const once = await renderGraphvizSvg(model, { view: 'data' }, 'wasm')
    const twice = await renderGraphvizSvg(model, { view: 'data' }, 'wasm')
    expect(once).toBe(twice)
  })
})

/**
 * The drift-PR workflow is a template people copy. A renamed CLI flag would
 * leave it broken in every repository that copied it, and nothing else in the
 * suite would notice — the file is documentation as far as CI is concerned.
 */
describe('the drift pull request workflow template', () => {
  const template = readFileSync(new URL('../examples/drift-pr.yml', import.meta.url), 'utf8')

  it('uses flags the CLI actually has', () => {
    const cli = readFileSync(new URL('../src/cli.ts', import.meta.url), 'utf8')
    for (const flag of ['--write-model', '--config', '--out', '--exit-zero']) {
      expect(template).toContain(flag)
      expect(cli, `the workflow template passes ${flag}, which the CLI no longer defines`).toContain(flag)
    }
  })

  it('commits only the model, never the generated report', () => {
    // `create-pull-request` commits every change in the tree by default, and
    // the report is written next to it.
    expect(template).toContain('add-paths: architecture.yaml')
    expect(template).toContain('--out /tmp/drift-report.md')
  })

  it('reuses one branch, so a week of drift is one pull request', () => {
    expect(template).toContain('branch: driftwood/drift')
  })
})
