import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { loadModel } from '../src/model/validate.js'
import { graphvizRenderer, renderGraphvizSvg } from '../src/render/graphviz.js'

/**
 * The README embeds committed renders of the example. They are generated by
 * `npm run docs` and asserted in CI, but the failure they guard against —
 * changing the renderer and leaving the README showing the old picture — is
 * one you want to hear about before pushing, not after.
 */
describe('committed renders', () => {
  const model = loadModel(readFileSync(new URL('../examples/architecture.yaml', import.meta.url), 'utf8')).model!

  it('match what the renderer produces today', async () => {
    if (!(await graphvizRenderer.probe()).available) return // no WebAssembly here; CI covers it
    const committed = readFileSync(new URL('../docs/app.svg', import.meta.url), 'utf8')
    const fresh = await renderGraphvizSvg(model, { view: 'app', direction: 'LR' }, 'wasm')
    expect(fresh, 'docs/ is stale — run `npm run docs` and commit the result').toBe(committed)
  })

  it('are pinned to the bundled build, so a local `dot` cannot change them', async () => {
    if (!(await graphvizRenderer.probe()).available) return
    // Same call twice: layout must be byte-deterministic, or the freshness
    // check in CI would fail at random.
    const once = await renderGraphvizSvg(model, { view: 'data' }, 'wasm')
    const twice = await renderGraphvizSvg(model, { view: 'data' }, 'wasm')
    expect(once).toBe(twice)
  })
})
